### PR TITLE
Fix bugs related to 'Collapse-all' button

### LINKED ISSUE #138: FAQ -- collapse all
### Problem  

Now that individual FAQs aren't auto-collapsed when another is expanded, it's possible to manually expand all FAQs. When all FAQs have been manually expanded, the last item on the navbar says "Expand All", but clicking "Expand All" does nothing except change the last item to be "Close All"

### Solution  

When all FAQs are expanded (regardless of how), the last item on the navbar should automatically be "Close All".

### LINKED ISSUE #157: improve FAQ collapse behavior
Issue:

When user has expanded FAQs and is viewing near the bottom of the FAQs, clicking "Collapse All" causes the user to suddenly be viewing the bottom of the page, with no good visual indication they're still on `/faq` except for the URL itself. On desktop, the user sees the "Group Income Shorts" and footer section of the page; on mobile, the user sees merely the footer.

It would be a better user experience to leave some portion of the FAQ visible. The FAQ navbar is sufficient.

https://github.com/user-attachments/assets/a3e01106-d876-45e3-ae51-f26d32bb265c
Note: this happens regardless of whether user manually scrolls to the lower faqs or clicks a navbar link to get there. 

Solution:

When user clicks "collapse all" ensure the page does not scroll down beyond the lowest point at which the FAQ navbar remains visible.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #138 
closes #157

### CODE REVIEW

File: src/components/FAQ.vue [hunk 1]
```diff
@@ -180,6 +181,12 @@ export default {
       expandAll: false
     }
   },
+  computed: {
+    allItemsExpanded () {
+      const allQuestions = this.faqs.flatMap(block => block.qa)
+      return allQuestions.every(q => q.active)
+    }
```
Comment (SebinSong) [inline src/components/FAQ.vue]: As opposed to the previous logic where the component has a flag that governs whether all items are expanded/collapsed, added a computed prop that checks it the whole time.

**Comment by SebinSong** [comment]
Just updated this PR with the work for issue #157 as they are both issues related to 'Collapse-all' button's behaviour in `/faq` page.

Clicking on collapse-all will scroll the page to `General` section like below:

**Review by taoeffect — APPROVED** [review]
Nice!
