### PR TITLE
#69 - Fix bugs in the main page

### LINKED ISSUE #69: Typos & links on homepage
I found a few typos & missing/incorrect links on the homepage:

- "Get Started" button just above fold doesn't work (leads to 404)
- "Learn more about Basic Income" should be a link to FAQ
- "Why it matters?" should not have a "?" (change to "Why it matters")
- Under "Contribute", "independet" should be "independent"
- "Shelter Protocol" should now link to "https://shelterprotocol.net"
- In "How to get started" section 2 at bottom, "Read more about our technology" should be on its own line
- "Get Started" & "Sponsor" buttons near bottom of page don't work (lead to 404)

### PR DESCRIPTION
**Pull request by SebinSong**
closes #69

### CODE REVIEW

File: src/components/HomeAnimation.vue [hunk 1]
```diff
@@ -147,8 +147,8 @@
           <p class="is-title-2 c-container-title">Basic Income for your friends and family.</p>
 
           <div class="c-buttons">
-            <a class="c-navbar-item button is-big is-primary" href="/get-started">Get started</a>
-            <a class="c-navbar-item button is-big is-outlined" href="/sponsor">Sponsor</a>
+            <a class="c-navbar-item button is-big is-primary" href="/groupincome.org/get-started">Get started</a>
+            <a class="c-navbar-item button is-big is-outlined" href="/groupincome.org/sponsor">Sponsor</a>
```
Comment (taoeffect) [inline src/components/HomeAnimation.vue]: The issue with these `/groupincome.org/` links is that when we release the final website on groupincome.org, these `/groupincome.org/` prefixes need to not be here. They are only relevant because of how the Github Pages `okturtles.github.io` domain works.

Do you know know of a way we could update this project so that when we build the site for groupincome.org these links do not use this prefix, but when it's deployed on Github Pages it still works?

**Review by taoeffect — COMMENTED** [review]
Nicely done @SebinSong! I have a question regarding `/groupincome.org` links, see comment:

File: src/components/HomeAnimation.vue (hunk 1 above)
Comment (SebinSong) [reply src/components/HomeAnimation.vue]: @taoeffect one way is to use `import.meta.env.BASE_URL` instead of `/groupincome.org/` path prefix as mentioned in [here](https://docs.astro.build/en/reference/configuration-reference/#base), but let me take more time on researching for a better solution possible and get back to this thread.

**Comment by SebinSong** [comment]
@taoeffect Updated the PR with the changes where all `/groupincome.org/` prefixes are replaced with `import.meta.env.BASE_URL`. I actually spent several hours over a couple of days searching for something similar to `publicPath` build option in Webpack (reference [here](https://webpack.js.org/guides/public-path/)), which gracefully handles this kind of task(prefixing the paths to assets during build steps), but couldn't find it for Astro. so fell back to this solution using this.

Also as you can see in `package.json`, I added a command `npm run build:prod`, which allows us to customise the site url and the base path in `astro.config.mjs` while building the project into a static website.
I deployed this build outcome of `npm run build:prod` to [a test Heroku app here](http://test-group-income-org-87e4f008e53f.herokuapp.com/) and apparently it works well there.

Hope the updates look good.

File: astro.config.mjs [hunk 2]
```diff
@@ -27,13 +27,17 @@ const remarkEmbedPlugin = [remarkEmbedder.default, {
   }
 }];
 
+const { IS_PROD_BUILD } = process.env
 
 // https://astro.build/config
 export default defineConfig({
-  site: 'https://okturtles.github.io',
-  base: '/groupincome.org',
+  site: IS_PROD_BUILD === 'true' ? "https://our_prod_website_url.org" : 'https://okturtles.github.io',
```
Comment (taoeffect) [inline astro.config.mjs]: Is this `https://our_prod_website_url.org` supposed to be here? If so could you add a comment explaining why it's here and if it needs to be overwritten, how to do so?

File: src/_app.ts [hunk 3]
```diff
@@ -0,0 +1,18 @@
+import type { App } from 'vue'
+import { resolvePath } from '@/utils/helpers.js'
+
+const updateAttr = (attrName, el, relPath) => {
+  console.log('el, attrName, val: ', el, attrName, relPath)
```
Comment (taoeffect) [inline src/_app.ts]: If this comment is no longer necessary, it can be removed or commented out

File: src/pages/get-started.astro [hunk 4]
```diff
@@ -102,7 +102,7 @@ import Servers from '../components/Servers.vue';
 
   &:after {
     content: '';
-    background: url('/groupincome.org/svgs/bottom-curve-white.svg') no-repeat center bottom;
+    background: url('/svgs/bottom-curve-white.svg') no-repeat center bottom;
```
Comment (taoeffect) [inline src/pages/get-started.astro:105]: Does this need any special treatment?

**Review by taoeffect — CHANGES_REQUESTED** [review]
Great work @SebinSong! Nicely done figuring out how to get the links to work in both environments! 👏 👏 

While testing I found two issues that clicking "Blog" link in the page footer takes us to a non-existent `/articles` link (should be `/blog`).

Also, on your heroku site, links on the `/blog` page go to the `/groupincome.org` prefix, is that intentional or a mistake?

I also added some in-line questions.

File: src/pages/get-started.astro (hunk 4 above)
Comment (SebinSong) [reply src/pages/get-started.astro:105]: @taoeffect 
No, the baseURL is not necessary here. it correctly loads in both environments without it.

**Comment by SebinSong** [comment]
@taoeffect further update done according to your comments.
([The test heroku website](http://test-group-income-org-87e4f008e53f.herokuapp.com/) has been updated with the fix too)

**Review by taoeffect — APPROVED** [review]
Fantastic work @SebinSong! 👏
