### PR TITLE
#168 - Fix anchor links

### LINKED ISSUE #168: Fix #anchor links
### Problem

Here's a diff I'd like to apply to the project that modifies this:

Image

to this:

Image

```diff
diff --git a/src/components/GetStarted.vue b/src/components/GetStarted.vue
index 637183b..9720198 100644
--- a/src/components/GetStarted.vue
+++ b/src/components/GetStarted.vue
@@ -5,8 +5,8 @@
       <div class="c-feature-box-title">Choose a Server</div>
       <div class="c-feature-box-para">
         Use
-        <a href="https://groupincome.app" class="is-link">our official server</a>
-        , choose from a community of independently operated servers, or run your own!
+        <a href="https://groupincome.app" class="is-link">our official server</a>,
+        choose from <a class="is-link" v-href="'/get-started/#servers'">a list</a> of independently operated servers, or run your own!
       </div>
     </div>
 
diff --git a/src/components/Servers.vue b/src/components/Servers.vue
index 3df1d4c..e1100d2 100644
--- a/src/components/Servers.vue
+++ b/src/components/Servers.vue
@@ -1,5 +1,6 @@
 <template>
 <div class="grid">
+  <a name="servers"></a>
   <div class="grid-item" v-for="server in servers" :key="server.name">
     <div class="card">
       <div class="card-body l-server">
@@ -126,4 +127,4 @@ const servers = [{
   font-size: 0.875rem;
   line-height: 1.3rem;
 }
-</style>
\ No newline at end of file
+</style>
```

The problem is twofold:

1. Clicking the `a list` link does not scroll me to the `#servers` anchor on the `/get-started` page.
2. On the `/get-started` page, the same component is there, but this time the link isn't a link. Hover over it and you'll see that although it looks like a link, you can't actually click it for some reason.

### Solution

Apply the diff and then:

1. Make it so that clicking the link scrolls to the anchor properly
2. Fix the problem where the link isn't a link on the `/get-started` page

### PR DESCRIPTION
**Pull request by SebinSong**
closes #168

### CODE REVIEW

File: src/components/GetStarted.vue [hunk 1]
```diff
@@ -5,8 +5,8 @@
       <div class="c-feature-box-title">Choose a Server</div>
       <div class="c-feature-box-para">
         Use
-        <a href="https://groupincome.app" class="is-link">our official server</a>
-        , choose from a community of independently operated servers, or run your own!
+        <a href="https://groupincome.app" class="is-link">our official server</a>,
++       choose from <a class="is-link" v-href="'/get-started#servers'">a list</a> of independently operated servers, or run your own!
```
Comment (taoeffect) [inline src/components/GetStarted.vue:9]: Note the `+` at the start, it's OK I'll fix it though!

**Review by taoeffect — APPROVED** [review]
Nice work @SebinSong! I'm surprised that this wasn't simpler. I have a feeling it might have to do with some of the `gsap.js` page animation code that was added to the project. I'll open a separate issue to address all of that and merge now as it works and we need this fix asap!
